name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      MERGE_LABELS: "automerge,!work in progress"
      MERGE_REMOVE_LABELS: "automerge"
      MERGE_COMMIT_MESSAGE: "pull-request-description"
      MERGE_FORKS: "false"
      MERGE_RETRIES: "6"
      MERGE_RETRY_SLEEP: "10000"
      MERGE_REQUIRED_APPROVALS: "0"
      UPDATE_LABELS: ""
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - id: add_labels
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.comment.body, '/add-labels') }}
        with:
          labels: automerge