name: Auto Merge Pull Request

on:
  pull_request:
    types:
      - opened

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:

  merge-pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Code Checkout
      uses: actions/checkout@v4

    - name: Merge Request
      run: |
        git config --global user.email "victorvmaciel@gmail.com"
        git config --global user.name "Victor Maciel"
        git remote set-url origin "https://$GITHUB_TOKEN@github.com/victorvmaciel/app.git"

        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

        git fetch origin pull/$PR_NUMBER/head:PR_BRANCH
        git checkout PR_BRANCH
        git merge --no-ff PR_BRANCH
        git push origin PR_BRANCH
