name: Auto Merge Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  merge-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Code Checkout
      uses: actions/checkout@v2

    - name: Fusão do Pull Request
      run: |
        git config --global victorvmaciel@gmail.com 
        git config --global user.name "Victor Maciel"

        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

        git fetch origin pull/$PR_NUMBER/head:PR_BRANCH
        git checkout PR_BRANCH
        git merge --no-ff origin/main
        git push origin PR_BRANCH

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
