name: Hello World

on:
  pull_request:
    branches:
    - master


jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hi
        run: echo "Hello world!!"
      - name: update packages
        run: sudo apt update
